### ISSUE TITLE
Links on module names in code excerpts in grep results are broken

### ISSUE THREAD

**Issue by simbabque** [metacpan/metacpan-grep-front-end#10]
When searching on grep.metacpan.org the code excerpts in the results have module names (like `require Foo::Bar`) converted to metacpan links. Those links point to https://grep.metacpan.org/pod/Foo::Bar, which of course doesn't exist, so it leads to a 404 page. It should be https://metacpan.org/pod/Foo::Bar.

Here is an example:

Search: https://grep.metacpan.org/search?size=20&q=DBIC_TRACE_PROFILE&qd=&qft=
Broken link: https://grep.metacpan.org/pod/DBIx::Class::Storage::Debug::PrettyPrint
![screenshot](https://user-images.githubusercontent.com/1125067/27173578-776af5f2-51b9-11e7-9c2a-e6bc8a2c3db3.png)

This is because the link is relative. When I inspect the page, it shows:

    <a href="/pod/DBIx::Class::Storage::Debug::PrettyPrint">DBIx::Class::Storage::Debug::PrettyPrint</a>

Steps to reproduce:
---

- Go to https://grep.metacpan.org
- Search for `DBIC_TRACE_PROFILE`
- Scroll down to the result in `DBIx-Class`
- Click the link on `require DBIx::Class::Storage::Debug::PrettyPrint`

Suggested solution:
---

I see two possible solutions:
- Make the links in this view absolute.
- Make https://grep.metacpan.org/pod an alias of https://metacpan.org/pod.

----
I originally posted this as metacpan/metacpan-web#1919, but that was in the wrong repository.

**Comment by simbabque** [comment]
I found the culprit. It's in https://github.com/metacpan/metacpan-web/blob/b97dafc723d3f27b88c86da063880ee0ad884749/root/static/js/syntaxhighlighter.js#L88, where the path is absolute but without the host. 

>         // Link our dependencies
>         return code.replace(/(<code class="p(?:er)?l keyword">(use|package|require)<\/code> <code class="p(?:er)?l plain">)([A-Z_a-z][0-9A-Z_a-z]*(?:::[0-9A-Z_a-z]+)*)(.*?<\/code>)/g, '$1<a href="/' + destination + '/$3">$3</a>$4');
> 

That makes a lot of sense when we're on https://metacpan.org, but not so much on https://grep.metacpan.org. I think this is not something that I can just fix and PR. Instead, we should probably build a forward so that https://grep.metacpan.org/pod sends the user onwards to https://metacpan.org/pod.

**Comment by haarg** [comment]
I think the syntax highlighter should be made to have a configurable URL root.  For metacpan-web, it would be `/`, but it would be configured to be `https://metacpan.org/` for grep.metacpan.org.

**Comment by atoomic** [comment]
Agree, for grep.metacpan.org, it should always add the prefix https://metacpan.org/ 
When you are reading the content of a perl file, no reasons to go somewhere else, you just want some doc about a specific module.

**Comment by atoomic** [comment]
Waiting for feedbacks before merging the previous merge request #11

**Comment by simbabque** [comment]
From a user perspective I'd say this is fine if it works. I think this is not critical, but probably a lot of users will run into this error, so it's good if it's hotfixed. From a developer perspective I'd say you're right, it should be made configurable.
