### ISSUE TITLE
Equal sign missing?

### ISSUE THREAD

**Issue by xsawyerx** [metacpan/metacpan-grep-front-end#20]
Trying to search for `\$\[\s*=` provides results for `\$\[\s*`, but without the equal sign.

The [URL](https://grep.metacpan.org/search?q=%5C%24%5C%5B%5Cs*%3D&qd=&qft=).

**Comment by atoomic** [comment]
need to confirm this is fixed after auto-deploy from #21 which would happen pretty soon :-)

**Comment by atoomic** [comment]
confirm that this is fixed
