### ISSUE TITLE
Page 2 broken on searches with = 

### ISSUE THREAD

**Issue by toddr** [metacpan/metacpan-grep-front-end#24]
https://grep.metacpan.org/search?q=%5C%24%5C%5B%5Cs*%3D&qd=&qft=

Click on page 2

**Comment by toddr** [comment]
Encoding = seems to  work

https://grep.metacpan.org/search?p=2&qd=&qft=&qci=&q=\$\[\s*%3D

**Comment by atoomic** [comment]
this is fixed by 583e083
