### ISSUE TITLE
Recent searches sidebar display issues

### ISSUE THREAD

**Issue by ilmari** [metacpan/metacpan-grep-front-end#31]
The sidebar has too much whitespace on the left, and overflows into the main page content for long strings.  See attached screenshot.
![image](https://user-images.githubusercontent.com/72175/32896101-0957ddec-cada-11e7-84fb-d4ea8dd9413e.png)

**Comment by atoomic** [comment]
thanks for the report, this needs to be fixed, probably at the same time we could also limit the length to avoid issues like 'DECLARE_STORE_LC...' but also most important the recent searches need to be redesigned as they do not support any special option

**Comment by atoomic** [comment]
fixed by PR #32
