### ISSUE TITLE
Update the file cache when a commit changes

### ISSUE THREAD

**Issue by toddr** [metacpan/metacpan-grep-front-end#4]
the git repo that is being grepped is going to be updated hourly. The file cache needs to invalidate when HEAD changes.

**Comment by atoomic** [comment]
as discussed we are going to use a 24 hours cache policy, which will solve most of the issues

**Comment by atoomic** [comment]
even better the Dancer app is started regularly we are going to use the HEAD commit as part of the caching directory, we should also cleanup older cache directories
