### ISSUE TITLE
first search produces 503 error

### ISSUE THREAD

**Issue by tonycoz** [metacpan/metacpan-grep-front-end#64]
## Context

My first attempt at a search typically produces a 503 error:

Error 503 first byte timeout

first byte timeout
Error 54113

Details: cache-syd10155-SYD 1654215852 2321965435

Varnish cache server

Reloading the page displays the results.

## Process

[ordered list the process to finding and recreating the issue, example below]

1. search for something I haven't searched for before
2. wait while spinny with Grepping is displayed
3. 503 error is displayed

## Expected result

Display the results of the search

## Current result

503 error

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

[if relevant, include a screenshot - simply drag & drop a picture there]
![image](https://user-images.githubusercontent.com/166429/171761757-ead2bb07-39fb-42cd-a0e2-3369adc7ce47.png)

**Comment by atoomic** [comment]
at first glance the Varnish cache is probably coming from the CDN cache
we should either try to configure the CDN properly or consider a cache buster...

Will give it a try , as I cannot reproduce this error in development environement
but this is obviously an issue in production

**Comment by ranguard** [comment]
I changed the first byte timeout from 15 to 40 seconds - it can be increase do a max of 60 seconds

Search seemed to work first time for me - reopen if not!

**Comment by atoomic** [comment]
@ranguard I ve just noticed the issue while reaching the homepage with probably a cold cache
<img width="733" alt="Screen Shot 2023-04-29 at 12 57 00" src="https://user-images.githubusercontent.com/405282/235299089-ee4589dc-9c7e-4ee9-8375-4c16b676e189.png">

**Comment by ranguard** [comment]
https://grep.metacpan.org/ looking ok for me now?

**Comment by atoomic** [comment]
yes we are now hitting a warm varnish cache...
