### ISSUE TITLE
repo updates on bm-mc-02 to not seem to be updating grep.metacpan.org.

### ISSUE THREAD

**Issue by toddr** [metacpan/metacpan-grep-front-end#65]
Despite updates on these days...

```
commit e9bdf699c9eb8dba6255e014dad5b2b6a136ea86
Author: Todd Rinaldo <toddr@cpan.org>
Date:   Tue Apr 18 11:01:53 2023 -0500

    Update for Tue Apr 18 11:01:17 2023

commit 3689a03617e6dbed4c9d30d4948c537b8e47d970
Author: Todd Rinaldo <toddr@cpan.org>
Date:   Mon Apr 17 13:06:52 2023 -0500

    Update for Mon Apr 17 13:06:17 2023

commit ed4d9df4fbccc0299cd841ae1b675fb0796de936
Author: Todd Rinaldo <toddr@cpan.org>
Date:   Fri Apr 14 11:44:14 2023 -0500

    Update for Fri Apr 14 11:43:32 2023
```

The grep main page says there hasn't been an update since March 23 2023

![Screen Shot 2023-04-18 at 11 20 29 AM](https://user-images.githubusercontent.com/97892/232841038-e613b714-dece-4526-b59b-3d2f51bfa036.png)

**Comment by atoomic** [comment]
<img width="442" alt="Screen Shot 2023-04-27 at 17 37 54" src="https://user-images.githubusercontent.com/405282/234913829-77fa862b-d005-468d-b5ac-4c02db5882b7.png">

view
https://github.com/metacpan/metacpan-k8s/blob/main/apps/grep/deployment.yaml#L25
with the hourly update 
https://github.com/metacpan/metacpan-k8s/blob/main/apps/grep/cronjob.yaml
