### ISSUE TITLE
Grepping for a dist named Mojo.* behaves in a strange way.

### ISSUE THREAD

**Issue by guest20** [metacpan/metacpan-grep-front-end#7]
<img width="839" alt="screen shot 2017-05-18 at 13 08 38" src="https://cloud.githubusercontent.com/assets/3603869/26200075/dfee96fe-3bcc-11e7-9bd6-2c3522ea735b.png">

I had assumed that the dist name was a regex (a UX issue maybe).

For some reason `Mojo.*` was just ignored? The first match isn't as restricted in a way I would expect. There's no literal dot in the `ABNF-Grammar`, so it's not a glob and the dist name doesn't start with `Mojo`, so it's not a regex.

I guess that means that it's just matching everything?

**Comment by atoomic** [comment]
mmm seems like Mojo* does the job whereas Mojo.* just catch everything 

This is probably the expected result there
https://grep.metacpan.org/search?q=validate&qd=Mojo*&qft=

**Comment by atoomic** [comment]
should be ok once the server is restarted with the new code, need to confirm & close in a few

**Comment by atoomic** [comment]
seems ok now in production
