### ISSUE TITLE
Sponsor links

### ISSUE THREAD

**Issue by oalders** [metacpan/metacpan-grep-front-end#9]
We should remove promocodewatch from the list of sponsors. Our agreement with them extends to the front page of MetaCPAN only.

If the Perl Careers link was also cargo culted, then it should probably be removed as well just to reduce any confusion and to be fair to all of the sponsors involved.

I can't comment on the Cpanel link as you guys actually work for Cpanel, right?  ;)

**Comment by atoomic** [comment]
No problems to remove the promocodewatch from the list of sponsors.

No ideas what should be done for the other sponsor links, yes Todd & I are working for cPanel, this is the reason I've added the cPanel logo as we worked on this project during our work days, if you think this needs to be removed just let me know.

I do not know the sponsorship policy of metacpan

**Comment by oalders** [comment]
Thanks! I think the problem is that we don't have a published sponsorship policy.  I'm fine with the Cpanel logo since they've sponsored your work on this.  

The promocode watch link was from a paid sponsorship for a link from the front page of MetaCPAN.org  The Perl Careers link is a paid link as part of the meta::hack sponsorship, so it should probably be removed as well.

The links do eventually expire and I want to avoid conversations around "why is this sponsor on this page but my sponsor link get removed?"

We *may* eventually want to add the hosting sponsors to the grep site, but we can discuss that at some other point.  Nobody has asked for it yet, so it's a moot point, I think.

**Comment by atoomic** [comment]
@oalders I think we can close this request as it, or are you expecting some extra fixups ?

**Comment by oalders** [comment]
Yep, I'll close.  Thanks!
